import { Device, Motor, Valve, Sensor, Robot, Conveyor, Drive, Cylinder, MotorData, ValveData, SensorData, RobotData, ConveyorData, DriveData, TrendData, CylinderData } from "@/types/device.types";
import { Alarm } from "@/types/alarm.types";
import { Station } from "@/types/station.types";

// Combined Device mock data (BaseDevice + specific data)
export const mockMotors: Motor[] = [
  {
    id: "motor-1",
    name: "Main Drive Motor",
    type: "motor",
    status: "running",
    location: "Station A1",
    lastUpdate: new Date().toISOString(),
    data: {
      speed: 1450,
      maxSpeed: 1800,
      current: 12.4,
      maxCurrent: 15,
      power: 7.8,
      temperature: 65,
      load: 78,
      runtime: "4h 32m",
      speedTrend: "up",
    },
  },
  {
    id: "motor-2",
    name: "Feed Motor",
    type: "motor",
    status: "stopped",
    location: "Station A3",
    lastUpdate: new Date().toISOString(),
    data: {
      speed: 0,
      maxSpeed: 1500,
      current: 0,
      maxCurrent: 12,
      power: 0,
      temperature: 42,
      load: 0,
      runtime: "2h 15m",
      speedTrend: "neutral",
    },
  },
  {
    id: "motor-3",
    name: "Conveyor Motor",
    type: "motor",
    status: "error",
    location: "Station A6",
    lastUpdate: new Date().toISOString(),
    data: {
      speed: 0,
      maxSpeed: 2000,
      current: 0,
      maxCurrent: 20,
      power: 0,
      temperature: 88,
      load: 0,
      runtime: "1h 45m",
      speedTrend: "down",
    },
  },
];

export const mockValves: Valve[] = [
  {
    id: "valve-1",
    name: "Hydraulic Valve 01",
    type: "valve",
    status: "running",
    location: "Station A2",
    lastUpdate: new Date().toISOString(),
    data: {
      position: "open",
      positionPercent: 85,
      pressure: 120,
      flowRate: 45,
      actuatorStatus: "active",
      lastCycle: "2h ago",
    },
  },
  {
    id: "valve-2",
    name: "Hydraulic Valve 02",
    type: "valve",
    status: "stopped",
    location: "Station A5",
    lastUpdate: new Date().toISOString(),
    data: {
      position: "closed",
      positionPercent: 0,
      pressure: 0,
      flowRate: 0,
      actuatorStatus: "inactive",
      lastCycle: "5h ago",
    },
  },
];

export const mockSensors: Sensor[] = [
  {
    id: "sensor-1",
    name: "Temperature Sensor 01",
    type: "sensor",
    status: "running",
    location: "Station A2",
    lastUpdate: new Date().toISOString(),
    data: {
      value: 72.5,
      unit: "°C",
      min: 68.0,
      max: 75.2,
      avg: 71.8,
      alarmThreshold: 80.0,
      trendHistory: [70, 71, 72, 71, 73, 72, 72.5],
    },
  },
  {
    id: "sensor-2",
    name: "Temperature Sensor 02",
    type: "sensor",
    status: "warning",
    location: "Station A5",
    lastUpdate: new Date().toISOString(),
    data: {
      value: 78.2,
      unit: "°C",
      min: 65.0,
      max: 82.0,
      avg: 74.5,
      alarmThreshold: 80.0,
      trendHistory: [72, 74, 76, 77, 78, 78, 78.2],
    },
  },
];

export const mockRobots: Robot[] = [
  {
    id: "robot-1",
    name: "Welding Robot 01",
    type: "robot",
    status: "running",
    location: "Station A1",
    lastUpdate: new Date().toISOString(),
    data: {
      mode: "auto",
      program: "Weld Sequence A",
      programNumber: "#05",
      cycle: 145,
      totalCycles: 200,
      timeRemaining: "00:02:34",
      axisPositions: { x: 1250, y: -450, z: 820 },
    },
  },
  {
    id: "robot-2",
    name: "Welding Robot 02",
    type: "robot",
    status: "manual",
    location: "Station A6",
    lastUpdate: new Date().toISOString(),
    data: {
      mode: "manual",
      program: "Manual Operation",
      programNumber: "#00",
      cycle: 0,
      totalCycles: 0,
      timeRemaining: "00:00:00",
      axisPositions: { x: 0, y: 0, z: 0 },
    },
  },
];

export const mockConveyors: Conveyor[] = [
  {
    id: "conveyor-1",
    name: "Main Conveyor",
    type: "conveyor",
    status: "running",
    location: "Station A3",
    lastUpdate: new Date().toISOString(),
    data: {
      speed: 2.5,
      direction: "forward",
      materialCount: 847,
      capacity: 1000,
      loadPercentage: 85,
      length: 25,
    },
  },
];

export const mockDrives: Drive[] = [
  {
    id: "drive-1",
    name: "Positioning Drive X",
    type: "drive",
    status: "auto",
    location: "Station A4",
    lastUpdate: new Date().toISOString(),
    data: {
      actPosition: 1250.5,
      actPositionIndex: 2,
      enBackward: true,
      enForward: true,
      enPositioning: true,
      targetPositionIndex: 0,
      axisMoving: true,
      errorMessage: "",
    },
  },
  {
    id: "drive-2",
    name: "Positioning Drive Y",
    type: "drive",
    status: "error",
    location: "Station A4",
    lastUpdate: new Date().toISOString(),
    data: {
      actPosition: 450.0,
      actPositionIndex: 1,
      axisMoving: false,
      enBackward: true,
      enForward: true,
      enPositioning: true,
      targetPositionIndex: 0,
      errorMessage: "Axis fault: Following error exceeded",
    },
  },
  {
    id: "drive-3",
    name: "Positioning Drive Z",
    type: "drive",
    status: "stopped",
    location: "Station A1",
    lastUpdate: new Date().toISOString(),
    data: {
      actPosition: 820.0,
      actPositionIndex: 0,
      axisMoving: false,
      enBackward: true,
      enForward: true,
      enPositioning: true,
      targetPositionIndex: 0,
      errorMessage: "",
    },
  },
];

export const mockCylinders: Cylinder[] = [
  {
    id: "cylinder-1",
    name: "Clamping Cylinder",
    type: "cylinder",
    status: "running",
    location: "Station A1",
    lastUpdate: new Date().toISOString(),
    data: {
      model: "2-state",
      inWorkPosition: true,
      inHomePosition: false,
      enabled: true,
      enableHomePosition: true,
      enableWorkPosition: true,
      errorMessage: '',
      toHomePosition: false,
      toWorkPosition: false,
      timeout: 5000,
    },
  },
  {
    id: "cylinder-2",
    name: "Ejector Cylinder",
    type: "cylinder",
    status: "running",
    location: "Station A2",
    lastUpdate: new Date().toISOString(),
    data: {
      model: "2-state",
      inWorkPosition: false,
      inHomePosition: true,
      enabled: false,
      enableHomePosition: true,
      enableWorkPosition: true,
      errorMessage: '',
      toHomePosition: false,
      toWorkPosition: false,
      timeout: 3000,
    },
  },
  {
    id: "cylinder-3",
    name: "Lifter Cylinder",
    type: "cylinder",
    status: "error",
    location: "Station A3",
    lastUpdate: new Date().toISOString(),
    data: {
      model: "2-state",
      inWorkPosition: false,
      inHomePosition: false,
      enabled: true,
      enableHomePosition: true,
      enableWorkPosition: true,
      errorMessage: '',
      toHomePosition: false,
      toWorkPosition: false,
      timeout: 4000,
    },
  },
  {
    id: "cylinder-4",
    name: "Press Cylinder",
    type: "cylinder",
    status: "running",
    location: "Station A4",
    lastUpdate: new Date().toISOString(),
    data: {
      model: "2-state",
      inWorkPosition: false,
      inHomePosition: true,
      enabled: true,
      enableHomePosition: true,
      enableWorkPosition: true,
      errorMessage: '',
      toHomePosition: false,
      toWorkPosition: false,
      timeout: 6000,
    },
  },
];

export const mockTrendData: TrendData[] = Array.from({ length: 60 }, (_, i) => ({
  timestamp: new Date(Date.now() - (59 - i) * 60000).toLocaleTimeString(),
  value: 7.5 + Math.random() * 2,
  power: 7.5 + Math.random() * 2,
  temperature: 60 + Math.random() * 20,
}));

export const mockDevices = {
  motors: mockMotors,
  valves: mockValves,
  sensors: mockSensors,
  robots: mockRobots,
  conveyors: mockConveyors,
  drives: mockDrives,
  cylinders: mockCylinders,
};

// All devices as a flat array
export const allMockDevices: Device[] = [
  ...mockMotors,
  ...mockValves,
  ...mockSensors,
  ...mockRobots,
  ...mockConveyors,
  ...mockDrives,
  ...mockCylinders,
];

export const kpiData = {
  oee: { value: "87.3", unit: "%", trend: "up" as const, status: "normal" as const },
  productionRate: { value: "450", unit: "units/hr", trend: "up" as const, status: "normal" as const },
  downtime: { value: "12", unit: "min", trend: "down" as const, status: "warning" as const },
  efficiency: { value: "92.1", unit: "%", trend: "neutral" as const, status: "normal" as const },
};

export const mockStations: Station[] = [
  {
    id: "station-a1",
    name: "Station A1",
    location: "Soldering",
    mode: "auto",
    partOk: 1245,
    partNok: 12,
    totalParts: 1257,
    efficiency: 98.5,
    status: "auto",
    warning: "",
    message: "Inspecting part...",
  },
  {
    id: "station-a2",
    name: "Station A2",
    location: "AOI Inspection",
    mode: "auto",
    partOk: 1189,
    partNok: 8,
    totalParts: 1197,
    efficiency: 97.2,
    status: "auto",
    warning: "",
    message: "Waiting for parts...",
  },
  {
    id: "station-a3",
    name: "Station A3",
    location: "Crimping",
    mode: "setup",
    partOk: 956,
    partNok: 15,
    totalParts: 971,
    efficiency: 94.8,
    status: "warning",
    warning: "Operator intervention required",
    message: "Setup mode active",
  },
  {
    id: "station-a4",
    name: "Station A4",
    location: "Palletizing",
    mode: "error",
    partOk: 0,
    partNok: 0,
    totalParts: 0,
    efficiency: 0,
    status: "error",
    warning: "Emergency stop activated",
    message: "Emergency stop activated",
  },
  {
    id: "station-a5",
    name: "Station A5",
    location: "Packaging",
    mode: "auto",
    partOk: 1102,
    partNok: 6,
    totalParts: 1108,
    efficiency: 96.8,
    status: "auto",
    warning: "",
    message: "Packaging completed",
  },
  {
    id: "station-a6",
    name: "Station A6",
    location: "Loading",
    mode: "auto",
    partOk: 1089,
    partNok: 9,
    totalParts: 1098,
    efficiency: 95.9,
    status: "auto",
    warning: "",
    message: "Loading new batch...",
  },
];

export const stationDevices: Record<string, string[]> = {
  "station-a1": ["motor-1", "robot-1", "cylinder-1"],
  "station-a2": ["valve-1", "sensor-1", "cylinder-2"],
  "station-a3": ["motor-2", "conveyor-1", "cylinder-3"],
  "station-a4": ["drive-1", "cylinder-4"],
  "station-a5": ["sensor-2", "valve-2", "cylinder-5"],
  "station-a6": ["robot-2", "motor-3", "cylinder-6"],
};
